# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='periodo_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='periodo_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(choices=[('A', 'Administrador'), ('O', 'Operador')], max_length=1),
        ),
    ]
